### ISSUE TITLE
panic on NS SAREGISTER

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1214]
This does not crash the server, but it's concerning:

```
Jul 25 09:25:35 [redacted] oragono[112309]: 2020-07-25T07:25:35.886Z : error : internal   : Client caused panic: runtime error: invalid memory address or nil pointer dereference
Jul 25 09:25:35 [redacted] oragono[112309]: goroutine 1421245 [running]:
Jul 25 09:25:35 [redacted] oragono[112309]: runtime/debug.Stack(0xc0004a8ad0, 0x9f7bc0, 0xf986d0)
Jul 25 09:25:35 [redacted] oragono[112309]:         runtime/debug/stack.go:24 +0x9d
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Client).run.func1(0xc00018a700, 0xc00015d8c0)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/client.go:592 +0xa7
Jul 25 09:25:35 [redacted] oragono[112309]: panic(0x9f7bc0, 0xf986d0)
Jul 25 09:25:35 [redacted] oragono[112309]:         runtime/panic.go:969 +0x166
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Client).AlwaysOn(0x0, 0xc00018ae00)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/getters.go:205 +0x22
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*AccountManager).Verify(0xc00014d800, 0x0, 0xc00002a46d, 0x6, 0x0, 0x0, 0x0, 0x0)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/accounts.go:905 +0x8aa
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*AccountManager).SARegister(0xc00014d800, 0xc00002a46d, 0x6, 0xc00002a474, 0x5, 0x0, 0x0)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/accounts.go:915 +0xf6
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.nsSaregisterHandler(0xc00014d800, 0xc00018a700, 0xc0001ce0a0, 0xa, 0xc00025d570, 0x2, 0x2, 0xc000416480)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/nickserv.go:886 +0x9c
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.serviceRunCommand(0xc000064ba0, 0xc00014d800, 0xc00018a700, 0xc0000a58c0, 0xc0001ce0a0, 0xa, 0xc00025d570, 0x2, 0x2, 0xc0>
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/services.go:215 +0x694
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.servicePrivmsgHandler(0xc000064ba0, 0xc00014d800, 0xc00018a700, 0xc00002a462, 0x17, 0xc000416480)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/services.go:153 +0x16d
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.dispatchMessageToTarget(0xc00018a700, 0x0, 0x1, 0xc00002a450, 0x7, 0xc00002a458, 0x8, 0xc00002a462, 0x17, 0xc00022b440, .>
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/handlers.go:2046 +0x14c1
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.messageHandler(0xc00014d800, 0xc00018a700, 0x0, 0x0, 0xc00002a450, 0x7, 0xc000360600, 0x2, 0x2, 0x0, ...)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/handlers.go:2017 +0x357
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Command).Run.func1(0xc000416480, 0xc00018a700, 0xc0003cbd58, 0xc00014d800, 0x0, 0x0, 0xc00002a450, 0x7, 0xc000360600, 0>
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/commands.go:53 +0x145
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Command).Run(0xc0003cbd58, 0xc00014d800, 0xc00018a700, 0xc00015d8c0, 0x0, 0x0, 0xc00002a450, 0x7, 0xc000360600, 0x2, ..>
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/commands.go:54 +0x167
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Client).run(0xc00018a700, 0xc00015d8c0)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/client.go:687 +0x526
Jul 25 09:25:35 [redacted] oragono[112309]: github.com/oragono/oragono/irc.(*Server).RunClient(0xc00014d800, 0xb96ae0, 0xc0001e4d70)
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/client.go:364 +0x97b
Jul 25 09:25:35 [redacted] oragono[112309]: created by github.com/oragono/oragono/irc.(*NetListener).serve
Jul 25 09:25:35 [redacted] oragono[112309]:         github.com/oragono/oragono/irc/listeners.go:99 +0x234
Jul 25 09:25:35 [redacted] oragono[112309]: 2020-07-25T07:25:35.887Z : error : internal   : Disconnecting client and attempting to recover
```

**Comment by slingamn** [comment]
This does not need a changelog entry, since it was never in a stable release.
