### ISSUE TITLE
panic in ircfmt.Unescape

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1467]
reported by @mogad0n on a `/rehash`:

```
Dec 18 12:13:19 overs33r oragono[571794]: 2020-12-18T11:13:19.582Z : error : internal   : Client caused panic: runtime error: index out of range [0] with length 0
Dec 18 12:13:19 overs33r oragono[571794]: goroutine 1602620 [running]:
Dec 18 12:13:19 overs33r oragono[571794]: runtime/debug.Stack(0xc0005371a0, 0xa65ac0, 0xc0001f2c40)
Dec 18 12:13:19 overs33r oragono[571794]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Client).run.func1(0xc00031b880, 0xc000709340)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/client.go:644 +0xac
Dec 18 12:13:19 overs33r oragono[571794]: panic(0xa65ac0, 0xc0001f2c40)
Dec 18 12:13:19 overs33r oragono[571794]:         /usr/local/go/src/runtime/panic.go:969 +0x1b9
Dec 18 12:13:19 overs33r oragono[571794]: github.com/goshuirc/irc-go/ircfmt.Unescape(0xc000387720, 0x42, 0x42, 0xc000387720)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/vendor/github.com/goshuirc/irc-go/ircfmt/ircfmt.go:274 +0xb06
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Config).loadMOTD(0xc000190c00, 0x0, 0x0)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/config.go:1537 +0x3d7
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.LoadConfig(0x7ffe90656ee5, 0x17, 0xaa9457, 0x6, 0xc00009fad8)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/config.go:1321 +0x107b
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Server).rehash(0xc00003fc00, 0x0, 0x0)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/server.go:492 +0x198
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.rehashHandler(0xc00003fc00, 0xc00031b880, 0x0, 0x0, 0xc0003581e0, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/handlers.go:2519 +0xeb
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Command).Run.func1(0xc00033fa80, 0xc00031b880, 0xc00009fec8, 0xc00003fc00, 0x0, 0x0, 0xc00035>
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/commands.go:53 +0x15d
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Command).Run(0xc00009fec8, 0xc00003fc00, 0xc00031b880, 0xc000709340, 0x0, 0x0, 0xc0003581e0, >
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/commands.go:54 +0x185
Dec 18 12:13:19 overs33r oragono[571794]: github.com/oragono/oragono/irc.(*Client).run(0xc00031b880, 0xc000709340)
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/client.go:739 +0x55a
Dec 18 12:13:19 overs33r oragono[571794]: created by github.com/oragono/oragono/irc.(*Client).run
Dec 18 12:13:19 overs33r oragono[571794]:         /home/mogad0n/oragono/irc/client.go:744 +0x5a5
```

I don't think this is a DoS vulnerability because we only apply this to trusted input (constant strings, or the motd file).

**Comment by DanielOaks** [comment]
Yeah that's related to some weird behaviour in the colour parser. Shouldn't be a big drama to fix, thanks for the report ~

**Comment by slingamn** [comment]
I did a quick audit. The correct order of operations (pseudocode) is `sprintf(unescape(translate(str)))`; this is most common in the code and is safe. There are a couple places where we do `unescape(sprintf(str))` or `unescape(sprintf(translate(str)))`; this is always on trusted data, e.g.,

https://github.com/oragono/oragono/blob/94df158c90348afdf6e6c44a32d3374d5289c4d3/irc/server.go#L459

These are benign, but we should fix them for consistency.

**Comment by DanielOaks** [comment]
Nice, really good catches with those

**Comment by slingamn** [comment]
https://github.com/goshuirc/irc-go/pull/27
