### ISSUE TITLE
panic (handled) on ZNC commands when history is disabled

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1552]
This is not a DoS (it just disconnects the client). Reported by @szlend against 56bef19505d4850:

```
2021-02-21T20:11:21.224Z : error : internal   : Client caused panic: runtime error: invalid memory address or nil pointer dereference
goroutine 740 [running]:
runtime/debug.Stack(0xc0000bb568, 0x92e760, 0xd19fc0)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
github.com/oragono/oragono/irc.(*Client).run.func1(0xc0005af500, 0xc000492000)
        /redacted/oragono/irc/client.go:660 +0x94
panic(0x92e760, 0xd19fc0)
        /usr/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/oragono/oragono/irc.zncPlaybackListHandler(0xc0005af500, 0xc000028b2c, 0x9, 0xc00060e050, 0x1, 0x1, 0xc000714000)
        /redacted/oragono/irc/znc.go:210 +0x1c5
github.com/oragono/oragono/irc.zncPlaybackHandler(0xc0005af500, 0xc000028b2c, 0x9, 0xc00060e050, 0x1, 0x1, 0xc000714000)
        /redacted/oragono/irc/znc.go:95 +0x10e
github.com/oragono/oragono/irc.zncModuleHandler(0xc0005af500, 0xc000028b2c, 0x9, 0xc00060e050, 0x1, 0x1, 0xc000714000)
        /redacted/oragono/irc/znc.go:34 +0xe3
github.com/oragono/oragono/irc.zncHandler(0xc000600800, 0xc0005af500, 0x0, 0x0, 0xc000028b28, 0x3, 0xc00060e040, 0x2, 0x2, 0x0, ...)
        /redacted/oragono/irc/handlers.go:3391 +0x108
github.com/oragono/oragono/irc.(*Command).Run.func1(0xc000714000, 0xc0005af500, 0xc0000bbcd8, 0xc000600800, 0x0, 0x0, 0xc000028b28, 0x3, 0>
        /redacted/oragono/irc/commands.go:47 +0x126
github.com/oragono/oragono/irc.(*Command).Run(0xc0000bbcd8, 0xc000600800, 0xc0005af500, 0xc000492000, 0x0, 0x0, 0xc000028b28, 0x3, 0xc0006>
        /redacted/oragono/irc/commands.go:48 +0x185
github.com/oragono/oragono/irc.(*Client).run(0xc0005af500, 0xc000492000)
        /redacted/oragono/irc/client.go:758 +0x5f8
github.com/oragono/oragono/irc.(*Server).RunClient(0xc000600800, 0xa70e18, 0xc00052e660)
        /redacted/oragono/irc/client.go:410 +0xac5
created by github.com/oragono/oragono/irc.(*NetListener).serve
        /redacted/oragono/irc/listeners.go:99 +0x2f0
```

**Comment by slingamn** [comment]
From other uses of `GetHistorySequence`, the expectation is that the caller does a `nil` check.
