### ISSUE TITLE
testEchoMessageNotice can flake

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#238]
````
====================================================================== 
FAIL: testEchoMessageNotice (test_echo_message.EchoMessageTestCase)    
        <http://ircv3.net/specs/extensions/echo-message-3.2.html>
----------------------------------------------------------------------   
Traceback (most recent call last):              
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 430, in newf      
    return f(self)                                                 
  File "/data/shivaram/workspace/irctest/irctest/server_tests/test_echo_message.py", line 73, in f     
    extra_format=(m1, m2))
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 83, in assertEqual
    super().assertEqual(got, expects, fail_msg)
AssertionError: {'time': '2018-04-15T07:29:26.349Z'} != {'time': '2018-04-15T07:29:26.348Z'}
- {'time': '2018-04-15T07:29:26.349Z'} 
?                                 ^    

+ {'time': '2018-04-15T07:29:26.348Z'} 
?                                 ^    
 : Tags of forwarded and echoed messages differ: Message(tags={'time': '2018-04-15T07:29:26.349Z'}, prefix='baz!~f@127.0.0.1', command='NOTICE', params=['#chan', 'hello everyone']) Message(tags={'time': '2018-04-15T07:29:26.348Z'}, prefix='baz!~f@127.0.0.1', command='NOTICE', params=['#chan', 'hello everyone'])
----------------------------------------------------------------------
````

**Comment by slingamn** [comment]
Dupe of DanielOaks/irctest#8, closing.
