### ISSUE TITLE
server-time flakes on resume replay?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#483]
I got this nondeterministic failure on a recent master, i.e., containing #477:

````
Testing Oragono on specification(s): IRCv3.1, IRCv3.2, Oragono, RFC1459, RFC2812
..........ss.................ssss..................................sssssssss............F......ss......
======================================================================
FAIL: testResume (test_resume.ResumeTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 428, in newf
    return f(self)
  File "/data/shivaram/workspace/irctest/irctest/server_tests/test_resume.py", line 87, in testResume
    self.assertEqual(privmsgs[0].tags.get('time'), channelMsgTime)
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 81, in assertEqual
    super().assertEqual(got, expects, fail_msg)
AssertionError: '2019-05-12T08:50:45.168Z' != '2019-05-12T08:50:45.169Z'
- 2019-05-12T08:50:45.168Z
?                       ^
+ 2019-05-12T08:50:45.169Z
?                       ^


----------------------------------------------------------------------
Ran 103 tests in 16.438s

FAILED (failures=1, skipped=17)
````

This should be impossible after #477 because we're supposed to be storing the original server-time along with the message and sending any time we do a replay. This suggests that there's a code path or an edge case where this behavior doesn't work as expected.

**Comment by DanielOaks** [comment]
[Here](https://github.com/oragono/oragono/pull/477/files#diff-21bc3e27d4f09e2e50e2e407e30f610eR1099), could we be sending the original message without any time bundled, it gets assigned one from the function, and then we store our original timestamp in the history db or something? feels like one of the only ways this could occur.
