### ISSUE TITLE
invalid message generated on `JOIN #chan,`

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#679]
reported by @bogdomania

```
Dec 02 17:11:49 vps202336 oragono[26853]: 2019-12-02T22:11:49.473Z : error : internal : Error assembling message for sending: Cannot have an empty param, a param with spaces, or a param that starts with ':' before the last parameter
Dec 02 17:11:49 vps202336 oragono[26853]: goroutine 33 [running]:
Dec 02 17:11:49 vps202336 oragono[26853]: runtime/debug.Stack(0xc0000af9e8, 0xc0000ec700, 0x200)
Dec 02 17:11:49 vps202336 oragono[26853]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*Session).SendRawMessage(0xc000252900, 0xc000162ae0, 0x12, 0xa091aa, 0x3, 0xc000254570, 0x3, 0x3, 0xc0002545d0, 0x0, ...)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/client.go:1195 +0x390
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*ResponseBuffer).flushInternal(0xc0004ddd80, 0xc0001d0101, 0x0, 0x0)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/responsebuffer.go:243 +0x37a
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*ResponseBuffer).Send(...)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/responsebuffer.go:193
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*Command).Run(0xc0000afdb0, 0xc00019a580, 0xc0001df400, 0xc000252900, 0x0, 0x0, 0xc000467018, 0x4, 0xc000462610, 0x1, ...)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/commands.go:45 +0x3c5
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*Client).run(0xc0001df400, 0xc000252900, 0x0, 0x0)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/client.go:486 +0x8ee
Dec 02 17:11:49 vps202336 oragono[26853]: github.com/oragono/oragono/irc.(*Server).RunClient(0xc00019a580, 0xae66c0, 0xc000010d48, 0x0, 0x0, 0x0, 0x0)
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/client.go:281 +0x869
Dec 02 17:11:49 vps202336 oragono[26853]: created by github.com/oragono/oragono/irc.(*Server).createListener.func1
Dec 02 17:11:49 vps202336 oragono[26853]:         /home/oragono/go/src/github.com/oragono/oragono/irc/server.go:324 +0x156
```

**Comment by slingamn** [comment]
This is not a crash, we just print the stack trace (even though it isn't particularly informative now that everything goes through `ResponseBuffer`).

The actual line that causes this is

```go
rb.Add(nil, server.name, ERR_NOSUCHCHANNEL, client.Nick(), name, client.t("No such channel"))
```

where `name` is the empty string.

**Comment by slingamn** [comment]
This is actually fairly interesting. There are three reasons that the channel name can be invalid in an `ERR_NOSUCHCHANNEL`: being empty, starting with a colon, or containing a space. Freenode actually handles the second two incorrectly, although the error isn't severe:

````
TOPIC :
:wolfe.freenode.net 461 testnick_4357328 TOPIC :Not enough parameters
TOPIC ::
:wolfe.freenode.net 403 testnick_4357328 : :No such channel
TOPIC :#hi there
:wolfe.freenode.net 403 testnick_4357328 #hi there :No such channel
````

So, it might be preferable for us to send `461 ERR_NEEDMOREPARAMS` in the first case, but it's easiest for us to handle all three cases by converting the invalid parameter to a `*` and sending `403 ERR_NOSUCHCHANNEL` as usual.
