### ISSUE TITLE
release builds should use -trimpath

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#901]
https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies

```
-trimpath
	remove all file system paths from the resulting executable.
	Instead of absolute file system paths, the recorded file names
	will begin with either "go" (for the standard library),
	or a module path@version (when using modules),
```

**Comment by slingamn** [comment]
This works nicely:

```
2020-03-30T01:08:19.116Z : error : server : DEBUG CRASHSERVER executed by operator root
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93f6b2]

goroutine 52 [running]:
github.com/oragono/oragono/irc.debugHandler.func1()
	github.com/oragono/oragono/irc/handlers.go:722 +0x2
created by github.com/oragono/oragono/irc.debugHandler
	github.com/oragono/oragono/irc/handlers.go:719 +0xc4e
```

`grep shivaram oragono` also returns no results.
